name: mrmrs-test
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.8668591431342065
title: Test Fixtures for Grid Development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
