name: mrmrs-test
favicon: null
layout_spectrum: 0.38378
typography_spectrum: 0.38578
title: Test Fixtures for Grid Development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-66287116-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#adadad'
    - '#2e2e2e'
    - '#767676'
    - '#979797'
    - '#494949'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
